name: Daily Auto Commit (Clean Version)

on:
  schedule:
    # Runs daily at 2:00 AM UTC (adjust timezone as needed)
    - cron: '0 2 * * *'
  workflow_dispatch:
    # Allows manual triggering from GitHub UI

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Configure git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Update auto-commit tracker file
      run: |
        # Create/update a dedicated file for auto-commits
        echo "Last auto-commit: $(date -u +"%Y-%m-%d %H:%M:%S UTC")" > .auto-commit-tracker
        echo "This file is automatically updated daily to keep the Streamlit app active." >> .auto-commit-tracker
        
    - name: Commit and push changes
      run: |
        git add .auto-commit-tracker
        git commit -m "🤖 Daily auto-commit to keep Streamlit app active - $(date -u +"%Y-%m-%d")"
        git push origin main 