name: Manual Wake Up

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Custom commit message (optional)'
        required: false
        default: 'Manual wake-up commit'

jobs:
  wake-up:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Update auto-commit tracker
      run: |
        echo "Manual wake-up: $(date -u +"%Y-%m-%d %H:%M:%S UTC")" > .auto-commit-tracker
        echo "This file was manually updated to wake up the Streamlit app." >> .auto-commit-tracker
        
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .auto-commit-tracker
        git commit -m "🚀 ${{ github.event.inputs.message || 'Manual wake-up commit' }} - $(date -u +"%Y-%m-%d")"
        git push origin main 