name: Simple Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Echo test
      run: echo "This is a test workflow to verify the Run workflow button works" 